### ISSUE TITLE
Broken updates 1.2.8/1.2.9

### ISSUE THREAD

**Issue by xyCommander** [ITSpecialist111/ai_automation_suggester#76]
Hey,

until 1.2.7 everything worked fine on my HAss Yellow, nice and inspiring suggestions arrived.

After updating to 1.2.8 I just got a notification with something regarding "configuration flow". No restart and reconfiguration worked.

The 1.2.9 some minutes later made everything even worse. The mentioned notification disappeared, but the log shows an unknown config error. When trying to reconfigure the missing api-key, the whole system crashes. I had to disconnect the Yellow from electricity three times, before it came back to life. But nothing in the logs, every bit of data gone.

I downgraded to 1.2.7 et voila, everything works perfectly fine again. Maybe both updates should be withdrawn until further inspection...but thats just my opinion.

**Comment by ITSpecialist111** [comment]
Am troubleshooting currently - thanks for the heads up

**Comment by SnakeEater96** [comment]
under googleai the integration says connection error

**Comment by Stoony1** [comment]
me to connection error

**Comment by SnakeEater96** [comment]
when you change the settings than kill homeassistant

**Comment by Stoony1** [comment]
> when you change the settings than kill homeassistant

me to ha crash when i make changes on 2 ha instances...

**Comment by ITSpecialist111** [comment]
1.3.0 on it's way in the next few moments, thanks for the updates. issues: 
 All provider methods (process_with_google, process_with_mistral, etc.) are now always present, preventing the “object has no attribute …” error.
• Null‑safe lookup for area_id and other registry fields eliminates the NoneType has no attribute 'area_id'` crash.

**Comment by Stoony1** [comment]
Thank you very much for the fast help.
